# Generated by Django 2.1 on 2024-08-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='country_of_production',
            field=models.CharField(default='USA', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='yearly_rate',
            field=models.FloatField(default=0),
        ),
    ]
